id: smart-fridge-recipes
namespace: ai.smartfridge
description: AI Agent summarizes fridge image, then a linear flow generates and validates recipes.

inputs:
  - id: fridgeImage
    type: STRING
    displayName: Fridge Image (Base64 or URL)
    defaults: ""
  - id: inventory
    type: STRING
    displayName: Manual Inventory (JSON)
    defaults: "[]"
  - id: skillLevel
    type: SELECT
    displayName: Skill Level
    values: ["beginner", "intermediate", "advanced"]
    defaults: "beginner"
  - id: availableTimeMinutes
    type: INT
    defaults: 30
  - id: dietaryRestriction
    type: SELECT
    displayName: Dietary Restriction
    defaults: "None"
    values: ["None", "Vegetarian", "Vegan", "Pescatarian", "Keto", "Paleo", "Gluten-Free", "Halal"]
  - id: allergies
    type: STRING
    defaults: "None"

tasks:
  # =================================================================
  # STEP 1: AI AGENT - SUMMARIZE DATA
  # The Agent's output variable is 'textOutput' as per the documentation.
  # =================================================================
  - id: agent_summarizer
    type: io.kestra.plugin.ai.agent.AIAgent
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    systemMessage: |
      You are an image analysis specialist.
      1. If an image is provided, you MUST call the analyze_image tool.
      2. Your final output should ONLY be the comma-separated list of ingredients found.
      3. If no image is provided, use the manual inventory text.
    prompt: |
      Analyze the provided data and return a list of ingredients.
      Image Provided: {{ inputs.fridgeImage != '' }}
      Manual Inventory: {{ inputs.inventory }}
    tools:
      - type: io.kestra.plugin.ai.tool.KestraTask
        tasks:
          - id: analyze_image
            type: io.kestra.plugin.gemini.MultimodalCompletion
            apiKey: "{{ secret('GEMINI_API_KEY') }}"
            model: gemini-2.5-flash
            contents:
              - role: USER
                content: "Analyze the image and return a simple comma-separated list of ingredients."
              - role: USER
                content: "{{ inputs.fridgeImage }}"

  # =================================================================
  # STEP 2: GENERATE RECIPES (Linear Flow)
  # =================================================================
  - id: generate_recipes
    type: io.kestra.plugin.ai.completion.ChatCompletion
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    messages:
      - type: SYSTEM
        content: "Generate 3 recipes. Return JSON only (No Markdown): {pantryItemsUsed:[], shoppingList:[], recipes:[{...}]}"
      - type: USER
        # CORRECTED: Uses the documented 'textOutput' variable from the AIAgent
        content: |
          Ingredients Available: {{ outputs.agent_summarizer.textOutput }}
          Constraints: Diet={{ inputs.dietaryRestriction }}, Skill={{ inputs.skillLevel }}, Time={{ inputs.availableTimeMinutes }}m, Allergies={{ inputs.allergies }}

  # =================================================================
  # STEP 3: VALIDATE RECIPES (Linear Flow)
  # =================================================================
  - id: validate_recipes
    type: io.kestra.plugin.ai.completion.ChatCompletion
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    messages:
      - type: SYSTEM
        content: "Validate recipes. Return JSON ONLY (No Markdown): {isValid: boolean, violationReason: 'string'}"
      - type: USER
        content: |
          Recipes: {{ outputs.generate_recipes.textOutput }}
          Constraints: Diet={{ inputs.dietaryRestriction }}, Time={{ inputs.availableTimeMinutes }}m, Allergies={{ inputs.allergies }}

  # =================================================================
  # STEP 4: DECISION & REGENERATION (Linear Flow)
  # =================================================================
  - id: check_validation
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.validate_recipes.textOutput contains 'false' }}"
    then:
      - id: regenerate_recipes
        type: io.kestra.plugin.ai.completion.ChatCompletion
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          modelName: gemini-2.5-flash
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
        messages:
          - type: SYSTEM
            content: "Fix the recipes based on the violation. Return JSON only (No Markdown)."
          - type: USER
            # CORRECTED: Uses the documented 'textOutput' variable
            content: |
              Violation Report: {{ outputs.validate_recipes.textOutput }}
              Original Inventory: {{ outputs.agent_summarizer.textOutput }}
              Regenerate safe recipes.

  # =================================================================
  # FINAL OUTPUT
  # =================================================================
  - id: final_output
    type: io.kestra.plugin.core.output.OutputValues
    values:
      finalPlan: "{{ (outputs.regenerate_recipes.textOutput is defined) ? outputs.regenerate_recipes.textOutput : outputs.generate_recipes.textOutput }}"
      # CORRECTED: Uses the documented 'textOutput' variable
      inventoryUsed: "{{ outputs.agent_summarizer.textOutput }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: smartfridge-recipes-secret-key-12345
    inputs:
      fridgeImage: "{{ trigger.body.fridgeImage ?? '' }}"
      inventory: "{{ trigger.body.inventory ?? '[]' }}"
      skillLevel: "{{ trigger.body.skillLevel ?? 'beginner' }}"
      availableTimeMinutes: "{{ trigger.body.availableTimeMinutes ?? 30 }}"
      dietaryRestriction: "{{ trigger.body.dietaryRestriction ?? 'None' }}"
      allergies: "{{ trigger.body.allergies ?? 'None' }}"