id: smart-fridge-recipes
namespace: ai.smartfridge
description: Smart Fridge Assistant (Webhook Fixed)

inputs:
  - id: fridgeImage
    type: STRING
    displayName: Fridge Image (Base64 or URL)
    defaults: ""
  - id: inventory
    type: STRING
    displayName: Manual Inventory (JSON)
    defaults: "[]"
  - id: skillLevel
    type: SELECT
    displayName: Skill Level
    values: ["beginner", "intermediate", "advanced"]
    defaults: "beginner"
  - id: availableTimeMinutes
    type: INT
    displayName: Time (minutes)
    defaults: 30
  - id: dietaryRestriction
    type: SELECT
    displayName: Dietary Restriction
    defaults: "None"
    values: ["None", "Vegetarian", "Vegan", "Pescatarian", "Keto", "Paleo", "Gluten-Free", "Halal"]
  - id: allergies
    type: STRING
    displayName: Allergies
    defaults: "None"

tasks:
  # STEP 1: ANALYZE IMAGE
  - id: analyze_step
    type: io.kestra.plugin.core.execution.Labels
    labels:
      step: "analyzing"
  
  - id: determine_inventory
    type: io.kestra.plugin.gemini.MultimodalCompletion
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: gemini-2.5-flash
    contents:
      - role: USER
        content: |
          You are a food identification expert.
          1. If the image is provided, identify all food items.
          2. If the image is empty, look at the Manual Inventory: {{ inputs.inventory }}
          Return a simple comma-separated list of ingredients found.
      - role: USER
        content: "{{ inputs.fridgeImage }}"

  # STEP 2: GENERATE RECIPES
  - id: generate_recipes
    type: io.kestra.plugin.ai.completion.ChatCompletion
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    messages:
      - type: SYSTEM
        content: |
          You are a professional chef. Generate 3 recipes.
          RETURN VALID JSON ONLY (No Markdown). Structure:
          {
            "pantryItemsUsed": ["item1"],
            "shoppingList": ["item1"],
            "recipes": [{ "title": "Name", "ingredients": [], "instructions": [] }]
          }
      - type: USER
        content: |
          Ingredients Available: {{ outputs.determine_inventory.text ?? outputs.determine_inventory.content ?? "No ingredients found" }}
          Constraints:
          - Diet: {{ inputs.dietaryRestriction }}
          - Skill: {{ inputs.skillLevel }}
          - Time: {{ inputs.availableTimeMinutes }}m
          - Allergies: {{ inputs.allergies }}

  # STEP 3: VALIDATE RECIPES
  - id: validate_recipes
    type: io.kestra.plugin.ai.completion.ChatCompletion
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    messages:
      - type: SYSTEM
        content: |
          Validate recipes. Return JSON ONLY (No Markdown): 
          { "isValid": boolean, "violationReason": "string or null" }
      - type: USER
        content: |
          RECIPES: {{ outputs.generate_recipes.textOutput }}
          CONSTRAINTS: {{ inputs.allergies }}, {{ inputs.dietaryRestriction }}
          Are these safe?

  # STEP 4: DECISION & REGENERATION
  - id: check_validation
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.validate_recipes.textOutput contains 'false' }}"
    then:
      - id: regenerate_recipes
        type: io.kestra.plugin.ai.completion.ChatCompletion
        provider:
          type: io.kestra.plugin.ai.provider.GoogleGemini
          modelName: gemini-2.5-flash
          apiKey: "{{ secret('GEMINI_API_KEY') }}"
        messages:
          - type: SYSTEM
            content: "Fix the recipes. Return VALID JSON ONLY (No Markdown)."
          - type: USER
            content: |
              Violation: {{ outputs.validate_recipes.textOutput }}
              Original: {{ outputs.generate_recipes.textOutput }}
              Regenerate safe recipes.

  # FINAL OUTPUT
  - id: final_output
    type: io.kestra.plugin.core.output.OutputValues
    values:
      finalPlan: "{{ (outputs.regenerate_recipes.textOutput is defined) ? outputs.regenerate_recipes.textOutput : outputs.generate_recipes.textOutput }}"
      inventoryUsed: "{{ outputs.determine_inventory.text ?? outputs.determine_inventory.content }}"

# ============================================================
# TRIGGERS (FIXED)
# ============================================================
triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: smartfridge-recipes-secret-key-12345
    inputs:
      fridgeImage: "{{ trigger.body.fridgeImage ?? '' }}"
      inventory: "{{ trigger.body.inventory ?? '[]' }}"
      skillLevel: "{{ trigger.body.skillLevel ?? 'beginner' }}"
      availableTimeMinutes: "{{ trigger.body.availableTimeMinutes ?? 30 }}"
      dietaryRestriction: "{{ trigger.body.dietaryRestriction ?? 'None' }}"
      allergies: "{{ trigger.body.allergies ?? 'None' }}"