id: manage-inventory
namespace: ai.smartfridge
description: "Accepts fridge image as URL or base64, normalizes to a Kestra file, extracts items via Gemini vision, formats JSON via AI Agent, then saves to Firebase."

inputs:
  - id: userId
    type: STRING
    displayName: User ID
    defaults: "user_001"

  # IMPORTANT: this can be either an https:// URL OR a base64 string OR a data URI.
  - id: fridgeImage
    type: STRING
    displayName: Fridge Image (URL or Base64 or data URI)
    defaults: ""

  # Only needed when fridgeImage is RAW base64 (not a data URI like data:image/jpeg;base64,...)
  - id: fridgeImageMimeType
    type: STRING
    displayName: Image mimeType (used for raw base64)
    defaults: "image/jpeg"

  - id: manualInventory
    type: STRING
    displayName: Manual Items (comma-separated or JSON)
    defaults: ""

tasks:
  # ====================================================
  # STEP 0: NORMALIZE IMAGE INTO KESTRA INTERNAL STORAGE
  # ====================================================
  - id: prepare_image
    type: io.kestra.plugin.scripts.python.Script
    dependencies:
      - requests
      - kestra
    outputFiles:
      - "fridge_image"
    script: |
      import base64
      import requests
      from kestra import Kestra

      raw = """{{ inputs.fridgeImage }}""".strip()
      fallback_mime = """{{ inputs.fridgeImageMimeType }}""".strip() or "image/jpeg"

      if not raw:
          raise Exception("inputs.fridgeImage is empty. Provide an https:// URL, base64, or data URI.")

      mime = fallback_mime
      content_bytes = None

      # Case 1: public URL
      if raw.startswith("http://") or raw.startswith("https://"):
          r = requests.get(raw, timeout=60)
          r.raise_for_status()
          # prefer server-provided content-type if available
          mime = (r.headers.get("content-type") or fallback_mime).split(";")[0].strip()
          content_bytes = r.content

      # Case 2: data URI: data:image/jpeg;base64,XXXX
      elif raw.startswith("data:"):
          header, b64 = raw.split(",", 1)
          # header like: data:image/jpeg;base64
          mime = header.split(";")[0].replace("data:", "").strip() or fallback_mime
          content_bytes = base64.b64decode(b64)

      # Case 3: raw base64 only
      else:
          content_bytes = base64.b64decode(raw)

      with open("fridge_image", "wb") as f:
          f.write(content_bytes)

      Kestra.outputs({"mimeType": mime})

  # ====================================================
  # STEP 1: VISION ANALYSIS
  # ====================================================
  - id: analyze_vision
    type: io.kestra.plugin.gemini.MultimodalCompletion
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: gemini-2.5-flash
    contents:
      - content: |
          Analyze this image. List every single food item you see.
          Be specific about quantity (e.g. "1 bunch", "2 cartons").
          Do not use markdown or json here, just a plain text list.
      - content: "{{ outputs.prepare_image.outputFiles['fridge_image'] }}"
        mimeType: "{{ outputs.prepare_image.vars.mimeType ?? inputs.fridgeImageMimeType ?? 'image/jpeg' }}"

  # ====================================================
  # STEP 2: AI AGENT SUMMARIZATION (STRICT JSON)
  # ====================================================
  - id: inventory_agent
    type: io.kestra.plugin.ai.agent.AIAgent
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    systemMessage: |
      You are an Inventory Manager AI.
      Convert raw food descriptions into a strict JSON array.
      Rules:
      1. Deduplicate items.
      2. Normalize names (lowercase, singular).
      3. Assign categories: [dairy, produce, meat, pantry, frozen, beverages, other].
      4. Output ONLY JSON array (no markdown).
    prompt: |
      Vision raw text:
      "{{ outputs.analyze_vision.text }}"

      Manual input:
      "{{ inputs.manualInventory }}"

      Return ONLY a JSON array like:
      [{"name":"...", "quantity":"...", "category":"..."}]

  # ====================================================
  # STEP 3: SAVE TO FIREBASE (YOUR API)
  # ====================================================
  - id: save_inventory_firebase
    type: io.kestra.plugin.core.http.Request
    method: POST
    uri: "http://host.docker.internal:3000/api/firebase/inventory"
    contentType: application/json
    body: "{{ {'userId': inputs.userId, 'inventory': outputs.inventory_agent.textOutput} | json }}"

outputs:
  - id: visionRawText
    type: STRING
    value: "{{ outputs.analyze_vision.text }}"
  - id: finalJson
    type: STRING
    value: "{{ outputs.inventory_agent.textOutput }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: inventory-manager-webhook-key-12345
    inputs:
      userId: "{{ trigger.body.userId ?? 'user_001' }}"
      fridgeImage: "{{ trigger.body.fridgeImage ?? '' }}"
      fridgeImageMimeType: "{{ trigger.body.fridgeImageMimeType ?? 'image/jpeg' }}"
      manualInventory: "{{ trigger.body.manualInventory ?? '' }}"
